name: Seminario_EM
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - matplotlib
  - openpyxl
  - pip
  - pip:
      - streamlit
      - plotly
      - pymc>=5.0
      - arviz
      - xarray
      - watchdog